### ISSUE TITLE
Zero size on decomp file.

### ISSUE THREAD

**Issue by ccap86** [topche-katt/hlsavetool#1]
The decomp file was created, but it is empty (see below) I did notice though that I am not getting "Successfully decompressed to save file "HL-03-11.decomp"  which looks like you output if there are no issues. The game version latest build (June 4th patch)

I also used the -v but no new file or text was given: ...
/// 
E:\Mods\Hogwarts\HL Save Tool-1983-1-0-1717857939\HLSaveTool>hlsaves.exe -d-v HL-03-11.org HL-03-11.decomp
Hogwarts Legacy save file tool - decompress/compress RawDatabaseImage SQLite database.
Open source tool by @katt and @ifonlythatweretrue
If you face issues, run the tool with verbosity flag "-v" and submit us a ticket (attach save file & tool output)
Report issues at https://github.com/topche-katt/hlsavetool/issues.

Trying to decompress save file "HL-03-11.org"

E:\Mods\Hogwarts\HL Save Tool-1983-1-0-1717857939\HLSaveTool>
///
//////////////////////////////////////////////////////////////////////////////////
orig decomp w/ only -d flag
//////////////////
E:\Mods\Hogwarts\HL Save Tool-1983-1-0-1717857939\HLSaveTool>hlsaves.exe -d HL-03-11.org HL-03-11.decomp
Hogwarts Legacy save file tool - decompress/compress RawDatabaseImage SQLite database.
Open source tool by @katt and @ifonlythatweretrue
If you face issues, run the tool with verbosity flag "-v" and submit us a ticket (attach save file & tool output)
Report issues at https://github.com/topche-katt/hlsavetool/issues.

Trying to decompress save file "HL-03-11.org"

E:\Mods\Hogwarts\HL Save Tool-1983-1-0-1717857939\HLSaveTool>dir
 Volume in drive E is TOSHIBA EXT
 Volume Serial Number is 82A8-BF79

 Directory of E:\Mods\Hogwarts\HL Save Tool-1983-1-0-1717857939\HLSaveTool

06/08/2024  10:49 AM    <DIR>          .
06/08/2024  10:49 AM    <DIR>          ..
06/08/2024  10:49 AM                 0 HL-03-11.decomp
06/07/2024  10:46 PM           399,854 HL-03-11.org
06/08/2024  11:48 AM            23,040 hlsaves.exe
06/08/2024  11:34 AM             1,061 LICENSE
06/08/2024  10:21 AM           582,656 oo2core_9_win64.dll
06/08/2024  11:34 AM                84 README.md
               6 File(s)      1,006,695 bytes
               2 Dir(s)  272,928,808,960 bytes free

**Comment by topche-katt** [comment]
Hi @ccap86 - you should add `-v` as the last parameter, ex: `hlsaves.exe -d HL-03-11.org HL-03-11.decomp -v`
Try again and paste the output and attach the save file so I can test it myself.

**Comment by topche-katt** [comment]
An updated version of the tool should be available for download on nexus shortly.
