### ISSUE TITLE
Error Code 126

### ISSUE THREAD

**Issue by LauseKrauseeeeee** [topche-katt/hlsavetool#4]
When I try to decompress my save file I get "error code 126"

C:\Users\xxx\Downloads\HL Save Tool-1983-1-1-1717896575\HLSaveTool>.\hlsaves.exe -d HL-00-00.orig HL-00-00.decomp
Hogwarts Legacy save file tool - decompress/compress RawDatabaseImage SQLite database.
Open source tool by @katt and @ifonlythatweretrue
If you face issues, run the tool with verbosity flag "-v" and submit us a ticket (attach save file & tool output)
Report issues at https://github.com/topche-katt/hlsavetool/issues.

Trying to decompress save file "HL-00-00.orig"
[Error] LoadLibraryEx(oo2core_9_win64.dll) failed with error code 126.

(I wasn't able to upload the ".orig" save, I renamed it to ".zip")
[HL-00-00.zip](https://github.com/user-attachments/files/16113916/HL-00-00.zip)

(I can't do .\hlsaves.exe -d HL-00-00.orig HL-00-00.decomp -v because of win 11)

**Comment by LauseKrauseeeeee** [comment]
Nevermind, forgot an additional file :)

**Comment by efempic** [comment]
How do you solve it? I've go the same problem.

"[Error] LoadLibraryEx(oo2core_9_win64.dll) failed with error code 126."
