### ISSUE TITLE
[Error] LoadLibraryEx(oo2core_9_win64.dll) failed with error code 126.

### ISSUE THREAD

**Issue by TheSanguimancer** [topche-katt/hlsavetool#5]
[Info] Input file: HL-00-02.orig
[Info] Output file: HL-00-02.decomp
[Info] Input file size: 2503388 bytes
[Info] Input file memory buffer size: 2503388 bytes
[Info] GVAS File Header:
[Info]  Signature: 0x47564153
[Info]  Version: 2
[Info]  Package: 524
[Info]  Engine: 4.27.2 (2148712435)
[Info] Address of Base: 2665586843712
[Info] Address of RawDatabaseImage: 2665586845704
[Info] Head address 2665586843712 and size 1992 bytes
[Info] Head relative offset: 1992
[Info] FString of length [17] and value (RawDatabaseImage)
[Info] FString of length [14] and value (ArrayProperty)
[Info] ArrayProperty value length: 1240885 bytes
[Info] FString of length [13] and value (ByteProperty)
[Info] ByteProperty value length: 1240881 bytes
[Info] ByteProperty value signature: 0xC1832A9E
[Info] Tail address 2665588086654 and size 1260446 bytes
[Info] Tail relative offset: 1242942
[Info] Before processing RawDatabaseImage with -d command
[Info] Decompressing 1240881 bytes of data...
[Error] LoadLibraryEx(oo2core_9_win64.dll) failed with error code 126.

**Comment by Amin-Shahsavar** [comment]
same issue

**Comment by Amin-Shahsavar** [comment]
my issue was solved by installing the "oo2core_9_win64.dll"

but there is another issue: when I try to edit database 1 I edit it successfully but database 2 is steel encrypted...
what should I do?

**Comment by efempic** [comment]
I need help, I've got the same problem.

PS C:\Users\supuser\AppData\Roaming\Vortex\hogwartslegacy\mods\HL Save Tool-1983-1-1-1717896575\HLSaveTool> .\hlsaves.exe -d HL-00-00.orig HL-00-00.decomp -v
Hogwarts Legacy save file tool - decompress/compress RawDatabaseImage SQLite database.
Open source tool by @katt and @ifonlythatweretrue
If you face issues, run the tool with verbosity flag "-v" and submit us a ticket (attach save file & tool output)
Report issues at https://github.com/topche-katt/hlsavetool/issues.

Trying to decompress save file "HL-00-00.orig"
[Info] Input file: HL-00-00.orig
[Info] Output file: HL-00-00.decomp
[Info] Input file size: 932038 bytes
[Info] Input file memory buffer size: 932038 bytes
[Info] GVAS File Header:
[Info]  Signature: 0x47564153
[Info]  Version: 2
[Info]  Package: 524
[Info]  Engine: 4.27.2 (2148719605)
[Info] Address of Base: 2391942763120
[Info] Address of RawDatabaseImage: 2391942765112
[Info] Head address 2391942763120 and size 1992 bytes
[Info] Head relative offset: 1992
[Info] FString of length [17] and value (RawDatabaseImage)
[Info] FString of length [14] and value (ArrayProperty)
[Info] ArrayProperty value length: 449869 bytes
[Info] FString of length [13] and value (ByteProperty)
[Info] ByteProperty value length: 449865 bytes
[Info] ByteProperty value signature: 0xC1832A9E
[Info] Tail address 2391943215046 and size 480112 bytes
[Info] Tail relative offset: 451926
[Info] Before processing RawDatabaseImage with -d command
[Info] Decompressing 449865 bytes of data...
[Error] LoadLibraryEx(oo2core_9_win64.dll) failed with error code 126.

**Comment by Amin-Shahsavar** [comment]
Hi.
You should install the " oo2core_9_win64.dll " from the download link that is in the installation tutorial

![Screenshot 2024-09-07 190908](https://github.com/user-attachments/assets/45053cf3-5c6c-4ef1-a51a-017a9e4c0755)

@efempic

**Comment by valhallrf** [comment]
Any help)

PS D:\Download\misc\Hogwarts Legacy\HLSaveTool> .\hlsaves.exe -d  HL-00-00.orig HL-00-00.decomp -v
Hogwarts Legacy save file tool - decompress/compress RawDatabaseImage SQLite database.
Open source tool by @katt and @ifonlythatweretrue
If you face issues, run the tool with verbosity flag "-v" and submit us a ticket (attach save file & tool output)
Report issues at https://github.com/topche-katt/hlsavetool/issues.
Trying to decompress save file "HL-00-00.orig"
[Info] Input file: HL-00-00.orig
[Info] Output file: HL-00-00.decomp
[Info] Input file size: 2257420 bytes
[Info] Input file memory buffer size: 2257420 bytes
[Info] GVAS File Header:
[Info]  Signature: 0x47564153
[Info]  Version: 2
[Info]  Package: 524
[Info]  Engine: 4.27.2 (2148600886)
[Info] Address of Base: 10195008
[Info] Address of RawDatabaseImage: 10196910
[Info] Head address 10195008 and size 1902 bytes
[Info] Head relative offset: 1902
[Info] FString of length [17] and value (RawDatabaseImage)
[Info] FString of length [14] and value (ArrayProperty)
[Info] ArrayProperty value length: 1126404 bytes
[Info] FString of length [13] and value (ByteProperty)
[Info] ByteProperty value length: 1126400 bytes
[Info] ByteProperty value signature: 0x53514C69
[Info] Tail address 11323379 and size 1129049 bytes
[Info] Tail relative offset: 1128371
[Info] Before processing RawDatabaseImage with -d command
[Info] Decompressing 1126400 bytes of data...
[Error] Compressed block at position 0 and signature 53514C69 does not match C1832A9E.

**Comment by gx570s** [comment]
@Amin-Shahsavar is correct. This issue is resolved by executing Step 2 of the installation process.
